# Generated by Django 3.1.5 on 2021-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_create_date', models.DateField(auto_now_add=True)),
                ('blog_time', models.TimeField(auto_now=True)),
                ('blog_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_name', models.CharField(max_length=255)),
                ('svg_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.CharField(max_length=1000)),
                ('project_view_link', models.URLField(max_length=255)),
                ('notes_reflection', models.TextField()),
                ('project_technology', models.ManyToManyField(to='api.Technologies')),
            ],
        ),
    ]
