# Generated by Django 3.1.5 on 2021-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='show_on_sidebar',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technologies',
            name='svg_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
