# Generated by Django 3.1.5 on 2021-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210726_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_preview',
            field=models.CharField(default='Initial content...', max_length=20),
            preserve_default=False,
        ),
    ]
