# Generated by Django 3.1.5 on 2021-08-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_blog_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_image',
            field=models.ImageField(default='netflix.png', upload_to='projects'),
            preserve_default=False,
        ),
    ]
