# Generated by Django 3.1.5 on 2021-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectmodel_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_time']},
        ),
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='technologies',
            name='svg_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
